services:
  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8888:8000"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodb_data: